spring.application.name=memorylane
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/memorylane
spring.datasource.username=postgres
spring.datasource.password=postgres123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App
server.port=8080

#JWT
jwt.secret=memorylane-super-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000

cloudinary.cloud-name=xnzocixe
cloudinary.api-key=382715938719839
cloudinary.api-secret=zELl8E4JMrgv99wRm8bPHK0BYnw